#app
server:
  port: 8087
spring:
  profiles:
    active: test
  #redis配置
#  redis:
#    host: 10.10.2.131
#    port: 6379
#    database: 0
#    timeout: 5000ms
#    pool:
#    max-active: 8
#    max-wait: 1ms
#    max-idle: 8
#    min-idle: 0
  redis:
    host: 192.168.1.121
    port: 6379
    database: 0
    timeout: 5000ms
    pool:
    max-active: 8
    max-wait: 1ms
    max-idle: 8
    min-idle: 0
#mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.dchb.model.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      # Sequence序列接口实现类配置 key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: h2
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  ##logging
  #logging:
  level: warn
 #打印sql
logging:
  level:
    com.dchb.mapper: debug
#自定义配置
app:
  filePath: "/home/admin"
  #filePath: "C:/TEMP"
        
     